apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-app
  labels:
    app: crm-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crm-app
  template:
    metadata:
      labels:
        app: crm-app
    spec:
      containers:
        - name: crm-app
          image: anggiat/crm-app:latest
          ports:
            - containerPort: 8070

---

apiVersion: v1
kind: Service
metadata:
  name: crm-app-service
spec:
  type: NodePort
  selector:
    app: crm-app
  ports:
    - port: 8070
      targetPort: 8070
      nodePort: 30002
